server:
  port: 8084
  servlet:
    context-path: /api/v1
  address: 0.0.0.0

spring:
  application:
    name: legal-connect-server

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/legal-connect?createDatabaseIfNotExist=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

endpoints:
  cases: cases
  document: document
  events: events
  notes: notes
  payments: payments
  review: review
  user: user
  portal: portal
  timeline-event: timeline-event

application:
  security:
    secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c

